### ISSUE TITLE
UUID generation fails when sysfs cannot be read

### ISSUE THREAD

**Issue by nylen** [ramsey/uuid#260]
```
$uuid = \Ramsey\Uuid\Uuid::uuid1();
```

This line of code fails in my app with the following error message:

> file_get_contents(/sys/class/net/eth0/address): failed to open stream: Permission denied

Related: #185 (needs error handling for this code that reads from sysfs)

I do not have any control over this server.  For now, I have commented out the following line in the `vendor` dir which is not ideal as a long-term fix but it got things working again:

https://github.com/ramsey/uuid/blob/f30bc1af81b1fdf5dec5ae085eb3ac2c59c32fe7/src/Provider/Node/SystemNodeProvider.php#L42

**Comment by ramsey** [comment]
@nylen, @defser: Please try out version 3.9.2 of ramsey/uuid and let me know if that resolves this issue. Specifically, commit https://github.com/ramsey/uuid/commit/b39ec78f6e7655676cc65c4081007b9823e7cbc7 is where I fixed this.

Thanks for reporting this, and I'm sorry it took so long for me to resolve it!

**Comment by Patrick-DIJ** [comment]
@ramsey Thanks for looking in to it, seems like this issue is not yet resolved properly. Had the same issue just now on Debian with GRsecurity patched Linux kernel with error: 
`grsec: denied attemp to access restricted sysfs entry /sys/devices/vif-o/net/eth0/address by /usr/local/php-7.3/sbin/php-fpm[php-fpm:106557] uid/euid:1506/1506 gid/egid:1506/1506, parent /usr/local/php-7.3/sbin/php-fpm[php-fpm:1724] uid/euid:0/0 gid/egid:0/0`

Updated to 3.9.2 but it did not resolve the error. maybe you can take another look at this problem?
